### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by Kordoj** [positron96/ESP32_CNC_Pendant#1]
when trying to compile there is a file link in GCodeDevice.h missing this flags an error \devices/GCodeDevice.h:6:26: fatal error: CommandQueue.h: No such file or directory compilation terminated.

**Comment by positron96** [comment]
Hi. That's strange because the `CommandQueue.h` is there in the root. How are you compiling the program, what pio version, what OS?

**Comment by positron96** [comment]
Let me get this straight, do you use "Visual Studio Code" or "Visual Studio"? You mention IDE, what IDE exactly are you talking about? Please be more precise so that I understand what you are dealing with.

Though it's possible, I don't recommend using Arduino IDE (and changing file extension to .ino) because you'd need to manage the libraries manually. In this case, the Arduino IDE complains about missing [etl](https://www.etlcpp.com/arduino.html) library, which you need to install manually. There are other required libraries, all listed in `platformio.ini`. 

I'd really try to solve the problem with platformio, that's probably a shorter path than going Arduino IDE way.

**Comment by Kordoj** [comment]
Ok so I found this link https://github.com/ETLCPP/etl/blob/master/include/etl/observer.h 
I downloaded the zip and put the etl folder within the devices folder and then back in VS I changed all the links from #include <etl/observer.h> to #include "etl/observer.h" and #include  <etl/vector.h> to #include  "../devices/etl/vector.h" etc and was able to build it successfully. I just need to upload it to the lolin32 card and work out the wiring fingers crossed. Hope this helps someone else.

**Comment by Kordoj** [comment]
Sorry yes I was using Visual Studio Code.  I have used it for Marlin before and some ESP32 test files. I find that VSC can have issues updated libraries and I have to uninstall and reinstall it. I'm sure it should be pulling the etl library down but not sure why it's not. I was trying Arduino IDE just as an alternative.

**Comment by positron96** [comment]
I've just noticed that etl library is somewhat broken in the latest version and if I build from scratch, my build fails on missing etl too. I've pinned library versions and rolled back etl, now it should download old but working version. Could you please check if it works for you? (to make sure platformio uses the specified version, just delete whole `.pio` folder in project folder)

Also, there is a schematic now here:
https://github.com/positron96/ESP32_CNC_Pendant/blob/master/docs/Schematic_espendant_2022-02-24.png
